name: 'Multi-sig gate'

on: pull_request

jobs:
  review-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr     = context.payload.pull_request;
            const author = pr.user.login;

            // Skip rule if YOU opened the PR
            if (author === 'Test-user-dev-t') return;

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: pr.number
            });

            const approvals = reviews.filter(r => r.state === 'APPROVED');

            if (approvals.length < 2) {
              core.setFailed(`Need ≥2 approvals (currently ${approvals.length}).`);
            }
